name: Second Workflow

env:
  msg: "This is env variable"

on:
  push:
    branches: [ "main-dev" ]

  workflow_dispatch:

jobs:
  Job_3:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run : echo $msg
      

